spring:
  profiles: test
  datasource:
    platform: h2
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    database: H2
    hibernate:
      ddl-auto: create-drop
  mail:
    username: username
    password: secret
    host: localhost
    port: 3025
my:
  testingemail: testaddress